In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
list1 = [1,2,3]

array = np.array(list1)
array

array([1, 2, 3])

In [ ]:
list1 = [1,2,3]
list2 = [4,5,6]

array = np.array([list1,list2])
array

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
list1 = [1,2,3]
list2 = [4,5,6]

array = np.hstack([list1,list2])
array

array([1, 2, 3, 4, 5, 6])

In [ ]:
list1 = [1,2,3]
list2 = [4,5,6]

array = np.vstack([list1,list2]).reshape(3,2)
array

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
list1 = [[1,2],[3,4],[5,6]]
list2 = [[7,8],[9,10],[11,12]]

array = np.hstack([list1,list2])
array

array([[ 1,  2,  7,  8],
       [ 3,  4,  9, 10],
       [ 5,  6, 11, 12]])

In [ ]:
list1 = [[1,2],[3,4],[5,6]]
list2 = [[7,8],[9,10],[11,12]]

array = np.vstack([list1,list2]).reshape(4,3)
array

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
list1 = [[1,2],[3,4],[5,6]]
list2 = [[7,8],[9,10],[11,12]]

array2 = np.hstack([list1,list2]).reshape(4,3)
array2

array([[ 1,  2,  7],
       [ 8,  3,  4],
       [ 9, 10,  5],
       [ 6, 11, 12]])

In [ ]:
np.zeros(3)

(3,)

In [ ]:
list1 = [[1,2],[3,4],[5,6]]
list2 = [[7,8],[9,10],[11,12]]

array = np.hstack([list1,list2])
array

array([[ 1,  2,  7,  8],
       [ 3,  4,  9, 10],
       [ 5,  6, 11, 12]])

In [ ]:
array = np.random.randint(40,100,10)
array.max()

97

In [ ]:
vector = np.array(range(10))
my_slice = vector[3:7]
my_slice[:] = 20
print(vector)

[ 0  1  2 20 20 20 20  7  8  9]


In [ ]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
matrix = np.array(range(1,10)).reshape((3,3))
#matrix[0,0]
#matrix[0][0] 
#matrix[2,2]  
# matrix[2][2] 

output = np.array([1,2,3]).reshape(3,1)
output

matrix[2:3,:3]


array([[7, 8, 9]])